version: "3.9"

services:
  Cosmetic:
    image: "Cosmetic"
    restart: always
    ports: 
        - localhost:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

  mongo-express:
    container_name: mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - Cosmetic
    ports:
      - '8080:8081'
    environment:
      - ME_CONFIG_MONGODB_URL=mongodb://Cosmetic:27017
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb

volumes: 
  mongodb_data:
  mongodb_config: